name: FUS
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 0.1.3
  provider: 4.3.2+1
  flutter_screenutil: 2.3.1
  cached_network_image: 2.3.1
  flutter_sound: 5.1.1
  flutter_easyloading: 1.2.0
  permission_handler: 5.0.1+1
  path_provider: 1.6.14
  uuid: 2.2.2
  intl: 0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/asscre.png
    - assets/404.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: iconfont
      fonts:
        - asset: assets/iconfont.ttf
